import { create } from 'zustand';
import { OceanZoneId, TimeOfDayId, ZonePreset, TimeModifier, OceanState } from '../types/ocean';

export const ZONE_PRESETS: Record<OceanZoneId, ZonePreset> = {
  reef: {
    id: 'reef',
    name: 'Arrecife Turquesa',
    typeLabel: 'Zona segura',
    bgColor: '#002b36',
    fogColor: '#004f60',
    fogNear: 1.5,
    fogFar: 75.0,
    ambientColor: '#006688',
    ambientIntensity: 0.85,
    sunColor: '#fff5e6',
    sunIntensity: 3.2,
    sunPosition: [10, 25, 10],
    hemisphereTopColor: '#b4f1f8',
    hemisphereBottomColor: '#0d3b2e',
    hemisphereIntensity: 0.8,
    pointLight1Color: '#00ffcc',
    pointLight1Intensity: 4.0,
    pointLight2Color: '#00e5ff',
    pointLight2Intensity: 4.0,
    baseDepth: 12.4,
    
    waterShallowColor: '#26bfd9',
    waterDeepColor: '#004070',
    waterOpacity: 0.75,
    sandCrestColor: '#d4c494',
    sandTroughColor: '#8c7e5a',
    causticColor: '#ebfaff',
    causticIntensity: 0.95,
    godRaysOpacity: 0.85,
    godRaysColor: '#e6f7ff',
  },
  kelp: {
    id: 'kelp',
    name: 'Bosque Verde',
    typeLabel: 'Zona misteriosa',
    bgColor: '#00140a',
    fogColor: '#002914',
    fogNear: 0.5,
    fogFar: 45.0,
    ambientColor: '#004d1c',
    ambientIntensity: 0.75,
    sunColor: '#a8f0b0',
    sunIntensity: 2.2,
    sunPosition: [5, 20, -5],
    hemisphereTopColor: '#60e078',
    hemisphereBottomColor: '#031a07',
    hemisphereIntensity: 0.7,
    pointLight1Color: '#33ff66',
    pointLight1Intensity: 5.0,
    pointLight2Color: '#00cc55',
    pointLight2Intensity: 3.5,
    baseDepth: 28.6,
    
    waterShallowColor: '#38cc77',
    waterDeepColor: '#003818',
    waterOpacity: 0.85,
    sandCrestColor: '#4a6042',
    sandTroughColor: '#1a2e16',
    causticColor: '#70ffaa',
    causticIntensity: 0.65,
    godRaysOpacity: 0.70,
    godRaysColor: '#c6f8d5',
  },
  depths: {
    id: 'depths',
    name: 'Profundidades',
    typeLabel: 'Zona peligrosa',
    bgColor: '#000410',
    fogColor: '#000820',
    fogNear: 0.2,
    fogFar: 30.0,
    ambientColor: '#001848',
    ambientIntensity: 0.45,
    sunColor: '#4070ff',
    sunIntensity: 1.0,
    sunPosition: [0, 15, 15],
    hemisphereTopColor: '#3060c0',
    hemisphereBottomColor: '#000418',
    hemisphereIntensity: 0.4,
    pointLight1Color: '#0066ff',
    pointLight1Intensity: 3.0,
    pointLight2Color: '#2200aa',
    pointLight2Intensity: 4.0,
    baseDepth: 95.0,
    
    waterShallowColor: '#103070',
    waterDeepColor: '#000820',
    waterOpacity: 0.92,
    sandCrestColor: '#1a2438',
    sandTroughColor: '#0a101c',
    causticColor: '#3080ff',
    causticIntensity: 0.25,
    godRaysOpacity: 0.35,
    godRaysColor: '#70a0ff',
  },
  cave: {
    id: 'cave',
    name: 'Cueva Oculta',
    typeLabel: 'Zona secreta',
    bgColor: '#020208',
    fogColor: '#050514',
    fogNear: 0.1,
    fogFar: 22.0,
    ambientColor: '#140c30',
    ambientIntensity: 0.35,
    sunColor: '#00e5ff',
    sunIntensity: 0.6,
    sunPosition: [-12, 8, -8],
    hemisphereTopColor: '#301850',
    hemisphereBottomColor: '#03010c',
    hemisphereIntensity: 0.3,
    pointLight1Color: '#ff00cc',
    pointLight1Intensity: 7.0,
    pointLight2Color: '#00ffff',
    pointLight2Intensity: 7.0,
    baseDepth: 42.1,
    
    waterShallowColor: '#602080',
    waterDeepColor: '#060414',
    waterOpacity: 0.95,
    sandCrestColor: '#281a38',
    sandTroughColor: '#0d0714',
    causticColor: '#d060ff',
    causticIntensity: 0.18,
    godRaysOpacity: 0.15,
    godRaysColor: '#e080ff',
  },
  abyss: {
    id: 'abyss',
    name: 'Abismo',
    typeLabel: 'Zona desconocida',
    bgColor: '#00040e',
    fogColor: '#010614',
    fogNear: 0.2,
    fogFar: 32.0,
    ambientColor: '#0f2042',
    ambientIntensity: 0.38,
    sunColor: '#3050a0',
    sunIntensity: 0.4,
    sunPosition: [0, 10, 0],
    hemisphereTopColor: '#243868',
    hemisphereBottomColor: '#040918',
    hemisphereIntensity: 0.48,
    pointLight1Color: '#00ffaa',
    pointLight1Intensity: 12.0,
    pointLight2Color: '#aa33ff',
    pointLight2Intensity: 12.0,
    baseDepth: 380.5,
    
    waterShallowColor: '#0d2248',
    waterDeepColor: '#020716',
    waterOpacity: 0.95,
    sandCrestColor: '#1c2b48',
    sandTroughColor: '#091224',
    causticColor: '#2050a0',
    causticIntensity: 0.15,
    godRaysOpacity: 0.10,
    godRaysColor: '#4070d0',
  },
};

export const TIME_MODIFIERS: Record<TimeOfDayId, TimeModifier> = {
  morning: {
    id: 'morning',
    sunColorTint: '#ffaa77',
    sunIntensityMultiplier: 0.75,
    sunPositionOffset: [-15, -5, 0],
    ambientIntensityMultiplier: 0.85,
    fogColorTint: '#331100',
    godRaysMultiplier: 0.8,
    causticIntensityMultiplier: 0.8,
  },
  day: {
    id: 'day',
    sunColorTint: '#ffffff',
    sunIntensityMultiplier: 1.0,
    sunPositionOffset: [0, 0, 0],
    ambientIntensityMultiplier: 1.0,
    fogColorTint: '#000000',
    godRaysMultiplier: 1.0,
    causticIntensityMultiplier: 1.0,
  },
  sunset: {
    id: 'sunset',
    sunColorTint: '#ff5533',
    sunIntensityMultiplier: 0.65,
    sunPositionOffset: [18, -8, -5],
    ambientIntensityMultiplier: 0.7,
    fogColorTint: '#220511',
    godRaysMultiplier: 0.6,
    causticIntensityMultiplier: 0.5,
  },
  night: {
    id: 'night',
    sunColorTint: '#3355aa',
    sunIntensityMultiplier: 0.2,
    sunPositionOffset: [0, -15, 10],
    ambientIntensityMultiplier: 0.35,
    fogColorTint: '#00020a',
    godRaysMultiplier: 0.05,
    causticIntensityMultiplier: 0.05,
  },
};

export const useOceanStore = create<OceanState>((set) => ({
  activeZoneId: 'reef',
  timeOfDayId: 'day',
  soundEnabled: true,
  currentDepth: 12.4,

  setZone: (zoneId) => set({ 
    activeZoneId: zoneId,
    currentDepth: ZONE_PRESETS[zoneId].baseDepth 
  }),
  setTimeOfDay: (timeId) => set({ timeOfDayId: timeId }),
  toggleSound: () => set((state) => ({ soundEnabled: !state.soundEnabled })),
  setCurrentDepth: (depth) => set({ currentDepth: depth }),
}));
