import { create } from 'zustand';
import { OceanZoneId, TimeOfDayId, ZonePreset, TimeModifier, OceanState } from '../types/ocean';

export const ZONE_PRESETS: Record<OceanZoneId, ZonePreset> = {
  reef: {
    id: 'reef',
    name: 'Arrecife Turquesa',
    typeLabel: 'Zona segura',
    bgColor: '#0f766e',
    fogColor: '#0f766e',
    fogNear: 1.0,
    fogFar: 45.0,
    ambientColor: '#0d9488',
    ambientIntensity: 1.25,
    sunColor: '#fff7ed',
    sunIntensity: 4.8,
    sunPosition: [25, 40, -10],
    hemisphereTopColor: '#38bdf8',
    hemisphereBottomColor: '#0f766e',
    hemisphereIntensity: 1.1,
    pointLight1Color: '#00ffcc',
    pointLight1Intensity: 4.0,
    pointLight2Color: '#00e5ff',
    pointLight2Intensity: 4.0,
    baseDepth: 12.4,
    
    waterShallowColor: '#38bdf8',
    waterDeepColor: '#0f766e',
    waterOpacity: 0.35,
    sandCrestColor: '#f5e6c8',
    sandTroughColor: '#e6d5b0',
    causticColor: '#fffbeb',
    causticIntensity: 2.2,
    godRaysOpacity: 0.95,
    godRaysColor: '#fff7ed',

    particleColor: '#e6ffff',
    particleSize: 3.5,
    particleSpeed: 0.8,
    bubbleRatio: 0.4,
    particleDensity: 800,
    bioluminescenceGlow: 0.0,
  },
  kelp: {
    id: 'kelp',
    name: 'Bosque Verde',
    typeLabel: 'Zona misteriosa',
    bgColor: '#002414',
    fogColor: '#00381e',
    fogNear: 2.0,
    fogFar: 65.0,
    ambientColor: '#005c24',
    ambientIntensity: 1.1,
    sunColor: '#a8f0b0',
    sunIntensity: 3.2,
    sunPosition: [5, 20, -5],
    hemisphereTopColor: '#60e078',
    hemisphereBottomColor: '#031a07',
    hemisphereIntensity: 0.95,
    pointLight1Color: '#33ff66',
    pointLight1Intensity: 6.0,
    pointLight2Color: '#00cc55',
    pointLight2Intensity: 4.5,
    baseDepth: 28.6,
    
    waterShallowColor: '#38cc77',
    waterDeepColor: '#003818',
    waterOpacity: 0.75,
    sandCrestColor: '#5c8054',
    sandTroughColor: '#2b4d24',
    causticColor: '#70ffaa',
    causticIntensity: 1.2,
    godRaysOpacity: 0.70,
    godRaysColor: '#c6f8d5',

    particleColor: '#a8f0c0',
    particleSize: 4.5,
    particleSpeed: 1.2,
    bubbleRatio: 0.25,
    particleDensity: 1400,
    bioluminescenceGlow: 0.2,
  },
  depths: {
    id: 'depths',
    name: 'Profundidades',
    typeLabel: 'Zona peligrosa',
    bgColor: '#001028',
    fogColor: '#001838',
    fogNear: 2.0,
    fogFar: 60.0,
    ambientColor: '#002860',
    ambientIntensity: 1.0,
    sunColor: '#4070ff',
    sunIntensity: 2.5,
    sunPosition: [0, 15, 15],
    hemisphereTopColor: '#3060c0',
    hemisphereBottomColor: '#000418',
    hemisphereIntensity: 0.8,
    pointLight1Color: '#0066ff',
    pointLight1Intensity: 5.0,
    pointLight2Color: '#2200aa',
    pointLight2Intensity: 6.0,
    baseDepth: 95.0,
    
    waterShallowColor: '#103070',
    waterDeepColor: '#000820',
    waterOpacity: 0.85,
    sandCrestColor: '#426396',
    sandTroughColor: '#203659',
    causticColor: '#50a0ff',
    causticIntensity: 1.0,
    godRaysOpacity: 0.35,
    godRaysColor: '#70a0ff',

    particleColor: '#70a0ff',
    particleSize: 3.0,
    particleSpeed: 0.5,
    bubbleRatio: 0.1,
    particleDensity: 900,
    bioluminescenceGlow: 0.4,
  },
  cave: {
    id: 'cave',
    name: 'Cueva Oculta',
    typeLabel: 'Zona secreta',
    bgColor: '#0a051c',
    fogColor: '#120a28',
    fogNear: 1.5,
    fogFar: 55.0,
    ambientColor: '#281450',
    ambientIntensity: 0.95,
    sunColor: '#00e5ff',
    sunIntensity: 2.0,
    sunPosition: [-12, 8, -8],
    hemisphereTopColor: '#482070',
    hemisphereBottomColor: '#060214',
    hemisphereIntensity: 0.75,
    pointLight1Color: '#ff00cc',
    pointLight1Intensity: 9.0,
    pointLight2Color: '#00ffff',
    pointLight2Intensity: 9.0,
    baseDepth: 42.1,
    
    waterShallowColor: '#602080',
    waterDeepColor: '#060414',
    waterOpacity: 0.85,
    sandCrestColor: '#6b4894',
    sandTroughColor: '#362054',
    causticColor: '#e070ff',
    causticIntensity: 0.9,
    godRaysOpacity: 0.25,
    godRaysColor: '#e080ff',

    particleColor: '#f0a0ff',
    particleSize: 4.0,
    particleSpeed: 0.6,
    bubbleRatio: 0.15,
    particleDensity: 1100,
    bioluminescenceGlow: 0.8,
  },
  abyss: {
    id: 'abyss',
    name: 'Abismo',
    typeLabel: 'Zona desconocida',
    bgColor: '#02091c',
    fogColor: '#05122b',
    fogNear: 1.5,
    fogFar: 55.0,
    ambientColor: '#122854',
    ambientIntensity: 0.9,
    sunColor: '#3050a0',
    sunIntensity: 1.8,
    sunPosition: [0, 10, 0],
    hemisphereTopColor: '#304880',
    hemisphereBottomColor: '#040d24',
    hemisphereIntensity: 0.7,
    pointLight1Color: '#00ffaa',
    pointLight1Intensity: 15.0,
    pointLight2Color: '#aa33ff',
    pointLight2Intensity: 15.0,
    baseDepth: 380.5,
    
    waterShallowColor: '#0d2248',
    waterDeepColor: '#020716',
    waterOpacity: 0.85,
    sandCrestColor: '#3b5f9e',
    sandTroughColor: '#1c3663',
    causticColor: '#4090ff',
    causticIntensity: 0.8,
    godRaysOpacity: 0.2,
    godRaysColor: '#4070d0',

    particleColor: '#00ffa8',
    particleSize: 5.0,
    particleSpeed: 0.4,
    bubbleRatio: 0.05,
    particleDensity: 1500,
    bioluminescenceGlow: 1.0,
  },
};

export const TIME_MODIFIERS: Record<TimeOfDayId, TimeModifier> = {
  morning: {
    id: 'morning',
    sunColorTint: '#ffaa77',
    sunIntensityMultiplier: 0.75,
    sunPositionOffset: [-15, -5, 0],
    ambientIntensityMultiplier: 0.85,
    fogColorTint: '#331100',
    godRaysMultiplier: 0.8,
    causticIntensityMultiplier: 0.8,
  },
  day: {
    id: 'day',
    sunColorTint: '#ffffff',
    sunIntensityMultiplier: 1.0,
    sunPositionOffset: [0, 0, 0],
    ambientIntensityMultiplier: 1.0,
    fogColorTint: '#000000',
    godRaysMultiplier: 1.0,
    causticIntensityMultiplier: 1.0,
  },
  sunset: {
    id: 'sunset',
    sunColorTint: '#ff5533',
    sunIntensityMultiplier: 0.65,
    sunPositionOffset: [18, -8, -5],
    ambientIntensityMultiplier: 0.7,
    fogColorTint: '#220511',
    godRaysMultiplier: 0.6,
    causticIntensityMultiplier: 0.5,
  },
  night: {
    id: 'night',
    sunColorTint: '#3355aa',
    sunIntensityMultiplier: 0.2,
    sunPositionOffset: [0, -15, 10],
    ambientIntensityMultiplier: 0.35,
    fogColorTint: '#00020a',
    godRaysMultiplier: 0.05,
    causticIntensityMultiplier: 0.05,
  },
};

export const useOceanStore = create<OceanState>((set) => ({
  activeZoneId: 'reef',
  timeOfDayId: 'day',
  soundEnabled: true,
  currentDepth: 12.4,

  setZone: (zoneId) => set({ 
    activeZoneId: zoneId,
    currentDepth: ZONE_PRESETS[zoneId].baseDepth 
  }),
  setTimeOfDay: (timeId) => set({ timeOfDayId: timeId }),
  toggleSound: () => set((state) => ({ soundEnabled: !state.soundEnabled })),
  setCurrentDepth: (depth) => set({ currentDepth: depth }),
}));
