import { create } from 'zustand';
import { OceanZoneId, TimeOfDayId, ZonePreset, TimeModifier, OceanState } from '../types/ocean';

export const ZONE_PRESETS: Record<OceanZoneId, ZonePreset> = {
  reef: {
    id: 'reef',
    name: 'Arrecife Turquesa',
    typeLabel: 'Zona segura',
    bgColor: '#002b36',
    fogColor: '#004f60',
    fogNear: 25,
    fogFar: 140,
    ambientColor: '#005577',
    ambientIntensity: 0.65,
    sunColor: '#fff5e6',
    sunIntensity: 2.8,
    sunPosition: [10, 25, 10],
    hemisphereTopColor: '#b4f1f8',
    hemisphereBottomColor: '#0d3b2e',
    hemisphereIntensity: 0.7,
    pointLight1Color: '#00ffcc',
    pointLight1Intensity: 3.5,
    pointLight2Color: '#00e5ff',
    pointLight2Intensity: 3.5,
    baseDepth: 12.4,
  },
  kelp: {
    id: 'kelp',
    name: 'Bosque Verde',
    typeLabel: 'Zona misteriosa',
    bgColor: '#00140a',
    fogColor: '#002914',
    fogNear: 15,
    fogFar: 85,
    ambientColor: '#003a15',
    ambientIntensity: 0.5,
    sunColor: '#d4f5d6',
    sunIntensity: 2.0,
    sunPosition: [5, 20, -5],
    hemisphereTopColor: '#a8f0b0',
    hemisphereBottomColor: '#05200a',
    hemisphereIntensity: 0.5,
    pointLight1Color: '#55ff77',
    pointLight1Intensity: 4.0,
    pointLight2Color: '#00cc66',
    pointLight2Intensity: 2.5,
    baseDepth: 28.6,
  },
  depths: {
    id: 'depths',
    name: 'Profundidades',
    typeLabel: 'Zona peligrosa',
    bgColor: '#000410',
    fogColor: '#000820',
    fogNear: 10,
    fogFar: 55,
    ambientColor: '#001035',
    ambientIntensity: 0.25,
    sunColor: '#5080ff',
    sunIntensity: 0.9,
    sunPosition: [0, 15, 15],
    hemisphereTopColor: '#4070c0',
    hemisphereBottomColor: '#000412',
    hemisphereIntensity: 0.3,
    pointLight1Color: '#0066ff',
    pointLight1Intensity: 2.0,
    pointLight2Color: '#3300cc',
    pointLight2Intensity: 3.0,
    baseDepth: 95.0,
  },
  cave: {
    id: 'cave',
    name: 'Cueva Oculta',
    typeLabel: 'Zona secreta',
    bgColor: '#020208',
    fogColor: '#050514',
    fogNear: 6,
    fogFar: 40,
    ambientColor: '#0a0820',
    ambientIntensity: 0.18,
    sunColor: '#00e5ff',
    sunIntensity: 0.5,
    sunPosition: [-12, 8, -8],
    hemisphereTopColor: '#201540',
    hemisphereBottomColor: '#020108',
    hemisphereIntensity: 0.2,
    pointLight1Color: '#ff00aa',
    pointLight1Intensity: 5.0,
    pointLight2Color: '#00ffff',
    pointLight2Intensity: 5.0,
    baseDepth: 42.1,
  },
  abyss: {
    id: 'abyss',
    name: 'Abismo',
    typeLabel: 'Zona desconocida',
    bgColor: '#000003',
    fogColor: '#010106',
    fogNear: 3,
    fogFar: 28,
    ambientColor: '#03030d',
    ambientIntensity: 0.08,
    sunColor: '#304080',
    sunIntensity: 0.15,
    sunPosition: [0, 10, 0],
    hemisphereTopColor: '#101530',
    hemisphereBottomColor: '#000000',
    hemisphereIntensity: 0.1,
    pointLight1Color: '#00ff88',
    pointLight1Intensity: 6.0,
    pointLight2Color: '#7700ff',
    pointLight2Intensity: 6.0,
    baseDepth: 380.5,
  },
};

export const TIME_MODIFIERS: Record<TimeOfDayId, TimeModifier> = {
  morning: {
    id: 'morning',
    sunColorTint: '#ffaa77',
    sunIntensityMultiplier: 0.75,
    sunPositionOffset: [-15, -5, 0],
    ambientIntensityMultiplier: 0.85,
    fogColorTint: '#331100',
  },
  day: {
    id: 'day',
    sunColorTint: '#ffffff',
    sunIntensityMultiplier: 1.0,
    sunPositionOffset: [0, 0, 0],
    ambientIntensityMultiplier: 1.0,
    fogColorTint: '#000000',
  },
  sunset: {
    id: 'sunset',
    sunColorTint: '#ff5533',
    sunIntensityMultiplier: 0.65,
    sunPositionOffset: [18, -8, -5],
    ambientIntensityMultiplier: 0.7,
    fogColorTint: '#220511',
  },
  night: {
    id: 'night',
    sunColorTint: '#3355aa',
    sunIntensityMultiplier: 0.2,
    sunPositionOffset: [0, -15, 10],
    ambientIntensityMultiplier: 0.35,
    fogColorTint: '#00020a',
  },
};

export const useOceanStore = create<OceanState>((set) => ({
  activeZoneId: 'reef',
  timeOfDayId: 'day',
  soundEnabled: true,
  currentDepth: 12.4,

  setZone: (zoneId) => set({ 
    activeZoneId: zoneId,
    currentDepth: ZONE_PRESETS[zoneId].baseDepth 
  }),
  setTimeOfDay: (timeId) => set({ timeOfDayId: timeId }),
  toggleSound: () => set((state) => ({ soundEnabled: !state.soundEnabled })),
  setCurrentDepth: (depth) => set({ currentDepth: depth }),
}));
